### ISSUE TITLE
Brightness doesn't save

### ISSUE THREAD

**Issue by ErikAnpin** [DanyGames2014/UniTweaks#17]
1. Join a server
2. Increase Brightness with slider
3. Disconnect
4. Rejoin server
5. Slider position is saved but Brightness is back to normal

**Comment by telvarost** [comment]
This is actually a bug with GlassConfigAPI 3. If you could post the issue there that would be awesome.
The bug specifically is that the @ValueOnVanillaServer tag is currently broken, and deleting your config when you join a server.

**Comment by telvarost** [comment]
https://github.com/Glass-Series/glass-config-api

**Comment by telvarost** [comment]
EDIT: Nvm, it was pointed out to me that this is in-fact a bug in UniTweaks

**Comment by DanyGames2014** [comment]
Fixed in UniTweaks 0.16.0
