### ISSUE TITLE
Port in MiscTweaks (used to be SmallInventory) Tweaks

### ISSUE THREAD

**Issue by telvarost** [DanyGames2014/UniTweaks#4]

**Comment by telvarost** [comment]
SmallInventoryTweaks was renamed to MiscTweaks

**Comment by telvarost** [comment]
Possibly can close this issue. It looks like MiscTweaks is more focused on non-vanilla content and UniTweaks is focused on QoL. So its possible their paths are quite diverged and unrelated as mods.

**Comment by DanyGames2014** [comment]
> Possibly can close this issue. It looks like MiscTweaks is more focused on non-vanilla content and UniTweaks is focused on QoL. So its possible their paths are quite diverged and unrelated as mods.

oki doki, i wanna move all planned features to the project anyway
