### ISSUE TITLE
Port in MojangFix

### ISSUE THREAD

**Issue by telvarost** [DanyGames2014/UniTweaks#7]

**Comment by telvarost** [comment]
It looks like js6pak is using a LGPL-3.0 license, so technically we don't need permission. We would just need to also license our mod under the LGPL-3.0 I think. Wynd's mod FinalBeta has a GPL-3.0-only license that is similar. Not really sure how licensing is going to work for this mod. What do you think?

**Comment by telvarost** [comment]
It was decided that a re-implementation would be attempted so as not to break the GPL license

**Comment by DanyGames2014** [comment]
Im eventually gonna get to this but auth and skin fix isleague above what im capable of

**Comment by telvarost** [comment]
I've created a compatibility fork of MojangFix. If you need any mixins disabled when UniTweaks is active just let me know. Otherwise, users can disable mixins themselves using the config :)
https://github.com/telvarost/MojangFix-StationAPI
